postgres:
  database: mydb
  user: zip1982b
  password: zhan99999
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5


host: 127.0.0.1
port: 8080


redis:
  REDIS_HOST: localhost
  REDIS_PORT: 6379